# Generated by Django 5.2.7 on 2025-12-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='folderId',
            new_name='FolderID',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='noteId',
            new_name='NoteID',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='user',
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='field_data',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='folder.folder'),
        ),
    ]
