# Generated by Django 5.2.7 on 2025-12-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
