# Generated by Django 5.2.6 on 2025-10-25 05:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deck', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stability', models.FloatField(default=0)),
                ('difficulty', models.FloatField(default=0)),
                ('state', models.IntegerField(choices=[(0, 'New'), (1, 'Learning'), (2, 'Review'), (3, 'Relearning')], default=0)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='deck.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='BasicCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card.card')),
                ('front_field', models.TextField()),
                ('back_field', models.TextField()),
            ],
            bases=('card.card',),
        ),
        migrations.CreateModel(
            name='IdentificationCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card.card')),
                ('front_field', models.TextField()),
                ('hidden_field', models.TextField()),
            ],
            bases=('card.card',),
        ),
        migrations.CreateModel(
            name='ImageOcclusionCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card.card')),
                ('front_field', models.TextField()),
                ('img_path', models.ImageField(upload_to='occlusion_images/')),
            ],
            bases=('card.card',),
        ),
    ]
