# Generated by Django 5.2.6 on 2025-10-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificationcard',
            name='front_field',
        ),
        migrations.RemoveField(
            model_name='imageocclusioncard',
            name='front_field',
        ),
    ]
