# Generated by Django 5.2.7 on 2025-12-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_remove_identificationcard_front_field_and_more'),
        ('deck', '0002_deck_slug_alter_deck_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basiccard',
            name='front_field',
        ),
        migrations.AddField(
            model_name='card',
            name='front_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.deck'),
        ),
        migrations.AlterField(
            model_name='card',
            name='state',
            field=models.IntegerField(choices=[(1, 'Learning'), (2, 'Review'), (3, 'Relearning')], default=1),
        ),
        migrations.AlterField(
            model_name='imageocclusioncard',
            name='img_path',
            field=models.ImageField(upload_to='static/card/occlusion_images/'),
        ),
    ]
